### ISSUE TITLE
Ieee802154RadioModel::isReceivedCorrectly -> Problem with Commit 09bbf2f5

### ISSUE THREAD

**Issue by michaelkirsche** [aarizaq/inetmanet-3.x#14]
The commit 09bbf2f504cb9865314b6699857b0c345639b503 introduced a small but serious error:

The return values for BITERROR and FRAMEOK were swapped which leads to the point where all correctly received packets are marked with BITERROR and therefore not send up to the CSMA link layer.

I've already fixed it in my INETMANET-2.0 fork: https://github.com/michaelkirsche/inetmanet-2.0/commit/8d55dbaa64e26ea18d3e0f91e78a6a64b5af9290

**Comment by aarizaq** [comment]
Thanks it was an stupid mistake, I included the changes just before to take my holidays and I was absolutely tired. I am going to fix this error

Date: Wed, 28 Aug 2013 09:05:25 -0700

**Comment by michaelkirsche** [comment]
No problem at all. I am grateful that you put so much work into porting INETMANET to the newest INET base. I'll keep you updated if I find any other bugs while working with INETMANET-2.0! 

Best regards,
Michael
