### ISSUE TITLE
dear aarizaq

### ISSUE THREAD

**Issue by bezualem** [aarizaq/inetmanet-3.x#26]
I am using your code  for the udp Video Broadcasting  (LTE video Broadcasting)but i couldn't find the following header files:VideoPacket_m.h ,UDPVideoData_m.h ,VideoPacket_m.h .when  the code run I receive  errors.could you mind  helping me with that. 
the files i am working on are UDPVideoStreamSvr2.cc and UDPVideoStreamCli2.cc
I am using inet-2.3.0 version .

best regards

**Comment by aarizaq** [comment]
the files *_m.h and *_m.cc are generated from the files *.msg. Omnet has a messages compiler that creates the h and cc files from the msg
It is possible to call the opp_msgc from the command line if the IDE, for a unknown circumstance, can call the message compiler

**Comment by bezualem** [comment]
I need to design  multi cell network for broadcasting video using simuLTE ,UDPVideoStreamSvr2.cc and UDPVideoStreamCli2.cc. To do this there are some points that are not very clear for me:
1.I need all eNodeBs broadcast the same video at same time .can UDPVideoStreamSvr2.cc and UDPVideoStreamCli2.cc. provide this  functionality? am I required to modify the code ? which class /part of the code I need to modify?

**Comment by aarizaq** [comment]
you can synchronize the video broadcast in every UDPVideoStreamSvr2 source if all start at the same time (parameter startBroadcast) and the time between frames is the same

The values of this parameters must be the same for all nodes and the value must be deterministic (you cannot use random distributions)

volatile double sendInterval @unit(s); // interval between sending video stream packets

volatile int packetLen @unit(B);  // length of a video packet in bytes

volatile int videoSize @unit(B);  // length of full a video stream in bytes

In this case it will exist a “perfect” synchronization between different nodes, if you use random distributions you will break the synchronization.

De: bezualem [mailto:notifications@github.com] 
Enviado el: martes, 05 de julio de 2016 18:08
Para: aarizaq/inetmanet-2.0 inetmanet-2.0@noreply.github.com
CC: Alfonso aarizaq_m@hotmail.com; Comment comment@noreply.github.com
Asunto: Re: [aarizaq/inetmanet-2.0] dear aarizaq (#26)

I need to design multi cell network for broadcasting video using simuLTE ,UDPVideoStreamSvr2.cc and UDPVideoStreamCli2.cc. To do this there are some points that are not very clear for me:
1.I need all eNodeBs broadcast the same video at same time .can UDPVideoStreamSvr2.cc and UDPVideoStreamCli2.cc. provide this functionality? am I required to modify the code ? which class /part of the code I need to modify?

**Comment by bezualem** [comment]
Thank you for your response ,it  helps me a lot
but,  I can't figure out how can I set  the time between frames are the same
I am sorry to bother you.
Thank you so much

**Comment by aarizaq** [comment]
The source can send frames a fixed intervals, but you cannot set the time between frames in the arrival

De: bezualem [mailto:notifications@github.com] 
Enviado el: sábado, 23 de julio de 2016 15:19
Para: aarizaq/inetmanet-2.0 inetmanet-2.0@noreply.github.com
CC: Alfonso aarizaq_m@hotmail.com; Comment comment@noreply.github.com
Asunto: Re: [aarizaq/inetmanet-2.0] dear aarizaq (#26)

Thank you for your response ,it helps me a lot
but, I can't figure out how can I set the time between frames are the same
I am sorry to bother you.
Thank you so much

**Comment by bezualem** [comment]
I truly appreciate your help in resolving the problem.

I want to create a network that contains two eNBs, three users ues per eNB. allocate 60% of RBs for  broadcasting  and 40% for uni caste  UDP video.I want to make sure that the nodes have to synchronize perfectly. and also 
how can I measure the throughput at each user(ue) ?
how can use input video traffic for this simulation?
if a created network consists of four eNBs and divides them in to two group,two eNBs per group. in a group eNBs are  share the same frequency channel.  how can I allocate different frequency channel for each group ?

the .ini file and NED source code is attached below 

Thank you for your kind cooperation.
[ini.txt](https://github.com/aarizaq/inetmanet-2.0/files/415280/ini.txt)

**Comment by aarizaq** [comment]
You can use the thrupmeter, there is a module that can mesure the throughput

---

De: bezualem notifications@github.com
Enviado: viernes, 12 de agosto de 2016 15:36:45
Para: aarizaq/inetmanet-2.0
Cc: Alfonso; Comment
Asunto: Re: [aarizaq/inetmanet-2.0] dear aarizaq (#26)

I truly appreciate your help in resolving the problem.

I want to create a network that contains two eNBs, three users ues per eNB. allocate 60% of RBs for broadcasting and 40% for uni caste UDP video.I want to make sure that the nodes have to synchronize perfectly. and also
how can I measure the throughput at each user(ue) ?
how can use input video traffic for this simulation?
if a created network consists of four eNBs and divides them in to two group,two eNBs per group. in a group eNBs are share the same frequency channel. how can I allocate different frequency channel for each group ?

the .ini file and NED source code is attached below

Thank you for your kind cooperation.
ini.txthttps://github.com/aarizaq/inetmanet-2.0/files/415280/ini.txt

##
