### ISSUE TITLE
StandardHost.ned issue with thruputmeter

### ISSUE THREAD

**Issue by pintoXgr** [aarizaq/inetmanet-3.x#31]
The code for connecting the thruputmeter to the UdpApps and the TcpApps doesn't work for more than one application.  
For example, for i=1 this code tries to connect the truUdpApp[1], but with i=0 check the last 2 rows, this is already connected and the simulation throws an error (gate already connected).

for i=0..numUdpApps-1, if hasThrugmeter {
            udpApp[i].udpOut --> truUdpApp[i].in;
            truUdpApp[i].out --> udp.appIn++;
            udpApp[i].udpIn <-- truUdpApp[i+1].out;
            truUdpApp[i+1].in <-- udp.appOut++;
        }

correct code should be this (similar for the tcpApps), which works

for i=0..numUdpApps-1, if hasThrugmeter {
            udpApp[i].udpOut --> truUdpApp[2*i].in;
            truUdpApp[2*i].out --> udp.appIn++;
            udpApp[i].udpIn <-- truUdpApp[2*i+1].out;
            truUdpApp[2*i+1].in <-- udp.appOut++;
        }

**Comment by aarizaq** [comment]
Fixed in 
https://github.com/aarizaq/inetmanet-3.x/commit/63612f7303a8c3808467f4312cd0b3a092acaa60
