### ISSUE TITLE
Missing dsrOptions (DSRPkt) in Qtenv Object Inspector

### ISSUE THREAD

**Issue by michalciolek** [aarizaq/inetmanet-3.x#33]
Hej,
I can not find the DSRPkt dsrOptions in the simulation view (for example, to view the packet routing path). How to turn it on?

![zrzut ekranu 2017-10-24 o 15 18 28](https://user-images.githubusercontent.com/4482555/31945174-abab6dc0-b8ce-11e7-8622-4d96b81f87b4.png)

**Comment by aarizaq** [comment]
Check the packet info, I think that the info write the information about the DSR packet.


De: Michał Ciołek [mailto:notifications@github.com]
Enviado el: martes, 24 de octubre de 2017 15:21
Para: aarizaq/inetmanet-3.x <inetmanet-3.x@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [aarizaq/inetmanet-3.x] Missing DSRPkt dsrOptions in packet treeview (#33)


Hej,
I can not find the DSRPkt dsrOptions in the simulation view (for example, to view the packet routing path). How to turn it on?

[zrzut ekranu 2017-10-24 o 15 18 28]<https://user-images.githubusercontent.com/4482555/31945174-abab6dc0-b8ce-11e7-8622-4d96b81f87b4.png>

**Comment by michalciolek** [comment]
Where is `pocket info`? I check everything in Object Inspector in `encapsulatedPacket (DSRPkt) (cPocket)` and `dsrOptions ` are missing.

**Comment by aarizaq** [comment]
Change in the API, replaced detailedInfo by str
Now the information is in base->info field



De: Michał Ciołek [mailto:notifications@github.com]
Enviado el: jueves, 26 de octubre de 2017 14:12
Para: aarizaq/inetmanet-3.x <inetmanet-3.x@noreply.github.com>
CC: Alfonso <aarizaq_m@hotmail.com>; Comment <comment@noreply.github.com>
Asunto: Re: [aarizaq/inetmanet-3.x] Missing dsrOptions (DSRPkt) in Qtenv Object Inspector (#33)


Where is pocket info? I check everything in Object Inspector in encapsulatedPacket (DSRPkt) (cPocket) and dsrOptions are missing.

**Comment by aarizaq** [comment]
https://github.com/aarizaq/inetmanet-3.x/commit/4b069259ebc3cc6dfec9f92d816145724c11566a#diff-20b8c69524eeb5ea0add2b95e7ca5148

De: Michał Ciołek [mailto:notifications@github.com]
Enviado el: jueves, 26 de octubre de 2017 14:12
Para: aarizaq/inetmanet-3.x <inetmanet-3.x@noreply.github.com>
CC: Alfonso <aarizaq_m@hotmail.com>; Comment <comment@noreply.github.com>
Asunto: Re: [aarizaq/inetmanet-3.x] Missing dsrOptions (DSRPkt) in Qtenv Object Inspector (#33)


Where is pocket info? I check everything in Object Inspector in encapsulatedPacket (DSRPkt) (cPocket) and dsrOptions are missing.

**Comment by michalciolek** [comment]
It is much better. Thanks!
