### ISSUE TITLE
Can't compile underTest/_4gsim

### ISSUE THREAD

**Issue by PavelVPV** [aarizaq/inetmanet-3.x#7]
I download inetmanet-2.0 from the master branch (these error also reproduced in the integration branch).

After trying to compile it by "$ make makefiles && make", I get errors that files under underTest/_4gsim has no enums NF_SUB_NEEDS_AUTH and etc.

I have been try investigate these errors and found that the configured Makefile not correctly define how to compile _4gsim.
It should have -DWITH_4GSIM definition or do not compile the _4gsim folder.

Please, fix it! :)

**Comment by aarizaq** [comment]
if you use the features to include _4gsim the flag is included Date: Sun, 24 Mar 2013 03:33:33 -0700

**Comment by PavelVPV** [comment]
I'm not using _4gsim feature, and option -DWITH_4GSIM is absent. But when I trying to compile framework throught  calling "make", _4gsim folder is included in Makefile and trying to be compiled.

**Comment by aarizaq** [comment]
if you active _4gsim in the project features the flag option will be included 

Date: Sun, 24 Mar 2013 12:10:15 -0700
