### ISSUE TITLE
Using DijkstraKshortest?

### ISSUE THREAD

**Issue by qupfer** [aarizaq/inetmanet-3.x#8]
Hi, can you give me a hint or an example, how the class DijkstraKshortest works?
I mean, how I get the cTopology to your Dijkstra functions? 

Thanks
qupfer

**Comment by aarizaq** [comment]
You can use the method setFromTopo(const cTopology *topo)

De: qupfer [mailto:notifications@github.com] 
Enviado el: martes, 09 de abril de 2013 0:33
Para: aarizaq/inetmanet-2.0
Asunto: [inetmanet-2.0] Using DijkstraKshortest? (#8)

Hi, can you give me a hint or an example, how the class C works?
I mean, how I get the cTopology to your Dijkstra functions? 

Thanks
qupfer

**Comment by qupfer** [comment]
Thanks for your answer,

but my knowledge about c++ is very small, so i'm not sure how i get a (correct) "const CTopology *topo". All my tries end with a crash or with a "Node not found" error. Of course, I set (or try to do it) the Root.
So I must ask: Can you or somebody else give me a bit more help ;-)

My actually testing-lines look like this:

```
DijkstraKshortest dj;
cTopology *topo= new cTopology;
topo->extractByProperty("node");
dj.setFromTopo(topo);
cTopology::Node *djnode = const_cast<cTopology*>(topo)->getNode(5);
NodeId target = djnode->getModuleId();
dj.setRoot(target);
dj.run();
```

but ends with crash.

Thank you again and I'm sorry to disturb you

**Comment by aarizaq** [comment]
I have uploaded a fix

De: qupfer [mailto:notifications@github.com] 
Enviado el: martes, 09 de abril de 2013 22:16
Para: aarizaq/inetmanet-2.0
CC: Alfonso
Asunto: Re: [inetmanet-2.0] Using DijkstraKshortest? (#8)

Thanks for your answer,

but my knowledge about c++ is very small, so i'm not sure how i get a (correct) "const CTopology *topo". All my tries end with a crash or with a "Node not found" error. Of course, I set (or try to do it) the Root.
So I must ask: Can you or somebody else give me a bit more help ;-)

My actually testing-lines look like this:

DijkstraKshortest dj;
cTopology _topo= new cTopology;
topo->extractByProperty("node");
dj.setFromTopo(topo);
cTopology::Node *djnode = const_cast<cTopology_>(topo)->getNode(5);
NodeId target = djnode->getModuleId();
dj.setRoot(target);
dj.run();

but ends with crash.

Thank you again and I'm sorry to disturb you
